blueprint:
  name: KNX - Media Player Volume % Receiver (by toben1997)
  description: 'This blueprint sets the volume level of a selected media player entity
    based on the percentage received from a specified KNX group address. It uses KNX
    data type 5.001.

    '
  author: toben1997
  source_url: https://github.com/toben1997/KNX-Home-Assistant/blob/main/KNX%20-%20Media%20Player%20Volume%20%25%20Receiver.yaml
  domain: automation
  input:
    knx_address:
      name: KNX Group Address
      description: The KNX group address to receive the volume level percentage. (DPT 5.001)
      selector:
        text: {}
    media_player_entity:
      name: Media Player Entity
      description: The media player entity to set the volume level.
      selector:
        entity:
          domain:
          - media_player
          multiple: false
mode: parallel
max_exceeded: silent
variables:
  knx_address: !input knx_address
  media_player_entity: !input media_player_entity
trigger:
- platform: event
  event_type: knx_event
  event_data:
    address: !input knx_address
action:
- service: media_player.volume_set
  target:
    entity_id: '{{ media_player_entity }}'
  data:
    volume_level: '{{ trigger.event.data.payload | int / 100 }}'
