blueprint:
  name: KNX - Media Player Volume % Send to DTP 5.001 (toben1997)
  description: 'This blueprint sends the volume level percentage from a selected media
    player entity to a specified KNX group address whenever the volume level changes.
    It uses KNX data type 5.001.

    '
  author: toben1997
  source_url: https://github.com/toben1997/KNX-Home-Assistant/blob/main/KNX%20-%20Media%20Player%20Volume%20%25%20Send%20to%20DTP%205.001.yaml
  domain: automation
  input:
    knx_address:
      name: KNX Group Address
      description: The KNX DTP 5.001 group address to send the volume level percentage.
      selector:
        text: {}
    media_player_entity:
      name: Media Player Entity
      description: The media player entity to monitor for volume level changes.
      selector:
        entity:
          domain:
          - media_player
          multiple: false
mode: parallel
max_exceeded: silent
variables:
  knx_address: !input knx_address
  media_player_entity: !input media_player_entity
trigger:
- platform: state
  entity_id: !input media_player_entity
  attribute: volume_level
action:
- service: knx.send
  data:
    address: '{{ knx_address }}'
    payload: '{{ (trigger.to_state.attributes.volume_level * 100) | int }}'
    type: percent
